# Generated by Django 3.2.1 on 2021-05-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetas',
            name='autor',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
